name: health_connect
description: "Health Connect Realtime Dashboard - Live steps & heart-rate monitoring"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  health: ^11.1.0
  convert: ^3.1.2
  crypto: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.14
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
